/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package inventario.ui;

/**
 *
 * @author blizc
 */
public class MainFrame extends javax.swing.JPanel {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }
    
    public void iniciar() {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                setVisible(true);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        modernJLabel1 = new inventario.ui.swing.ModernJLabel();
        modernJLabel2 = new inventario.ui.swing.ModernJLabel();
        modernJLabel3 = new inventario.ui.swing.ModernJLabel();
        modernJLabel4 = new inventario.ui.swing.ModernJLabel();
        jPanel2 = new javax.swing.JPanel();

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        modernJLabel1.setText("COMPRAS");
        jPanel1.add(modernJLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(199, 0, -1, -1));

        modernJLabel2.setText("INVENTARIO");
        jPanel1.add(modernJLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 0, -1, -1));

        modernJLabel3.setText("VENTAS");
        jPanel1.add(modernJLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(384, 0, -1, -1));

        modernJLabel4.setText("REPORTES");
        jPanel1.add(modernJLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(548, 0, -1, -1));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 630, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 630, 400));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private inventario.ui.swing.ModernJLabel modernJLabel1;
    private inventario.ui.swing.ModernJLabel modernJLabel2;
    private inventario.ui.swing.ModernJLabel modernJLabel3;
    private inventario.ui.swing.ModernJLabel modernJLabel4;
    // End of variables declaration//GEN-END:variables
}

