/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package inventario.ui.componets;

/**
 *
 * @author blizc
 */
public class InventoryPanel extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
    public InventoryPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        modernTable1 = new inventario.ui.swing.ModernTable();
        jLabel2 = new javax.swing.JLabel();
        modernComboBox1 = new inventario.ui.swing.ModernComboBox();
        modernButton1 = new inventario.ui.swing.ModernButton();
        modernButton2 = new inventario.ui.swing.ModernButton();

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        modernTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "PRODUCTO", "STOCK", "COSTO", "PRECIO"
            }
        ));
        jScrollPane1.setViewportView(modernTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 810, 360));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setText("Buscar Producto");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));
        jPanel1.add(modernComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, 500, -1));

        modernButton1.setText("Actualizar");
        modernButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modernButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(modernButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 440, -1, -1));

        modernButton2.setText("Agregar Producto");
        modernButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modernButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(modernButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 440, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 836, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void modernButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modernButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modernButton1ActionPerformed

    private void modernButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modernButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modernButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private inventario.ui.swing.ModernButton modernButton1;
    private inventario.ui.swing.ModernButton modernButton2;
    private inventario.ui.swing.ModernComboBox modernComboBox1;
    private inventario.ui.swing.ModernTable modernTable1;
    // End of variables declaration//GEN-END:variables
}
